// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCApjdzu1GA-Y7H9nWq30TWMXi8Rw9PRbA',
    appId: '1:89134278168:web:007c127635ce2a04ac056d',
    messagingSenderId: '89134278168',
    projectId: 'quizapp-df4cf',
    authDomain: 'quizapp-df4cf.firebaseapp.com',
    storageBucket: 'quizapp-df4cf.appspot.com',
    measurementId: 'G-D1ZBPTG7XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkakdNXJxEEWRoOW70kKP_C8tOycbaaws',
    appId: '1:89134278168:android:7c385512da13cd5fac056d',
    messagingSenderId: '89134278168',
    projectId: 'quizapp-df4cf',
    storageBucket: 'quizapp-df4cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnxHXO3ROwprsSxf47UnDPSfX58iaXEGc',
    appId: '1:89134278168:ios:e8b1712a9e40ca14ac056d',
    messagingSenderId: '89134278168',
    projectId: 'quizapp-df4cf',
    storageBucket: 'quizapp-df4cf.appspot.com',
    iosClientId: '89134278168-klrk2n175lunudmqr6tihgcnfbgbgse6.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnxHXO3ROwprsSxf47UnDPSfX58iaXEGc',
    appId: '1:89134278168:ios:e8b1712a9e40ca14ac056d',
    messagingSenderId: '89134278168',
    projectId: 'quizapp-df4cf',
    storageBucket: 'quizapp-df4cf.appspot.com',
    iosClientId: '89134278168-klrk2n175lunudmqr6tihgcnfbgbgse6.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp1',
  );
}
