// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2cpbOFSvxvr2qiD7g4WbTX6lSddYxZI',
    appId: '1:43506521486:web:a1306f4d51a73cb12180df',
    messagingSenderId: '43506521486',
    projectId: 'quizapp1-a364f',
    authDomain: 'quizapp1-a364f.firebaseapp.com',
    storageBucket: 'quizapp1-a364f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuVlsHVO_mZi7tSF7-jkHzt30EvuUI2ks',
    appId: '1:43506521486:android:24fbe40d702ea7f52180df',
    messagingSenderId: '43506521486',
    projectId: 'quizapp1-a364f',
    storageBucket: 'quizapp1-a364f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1FCRTtrY7iPewRQTZrbS5YSeK0u1cQAQ',
    appId: '1:43506521486:ios:994c33d66f056b192180df',
    messagingSenderId: '43506521486',
    projectId: 'quizapp1-a364f',
    storageBucket: 'quizapp1-a364f.appspot.com',
    iosClientId: '43506521486-eisiuhs8p5dsvtsbvtunb2ea361730ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1FCRTtrY7iPewRQTZrbS5YSeK0u1cQAQ',
    appId: '1:43506521486:ios:994c33d66f056b192180df',
    messagingSenderId: '43506521486',
    projectId: 'quizapp1-a364f',
    storageBucket: 'quizapp1-a364f.appspot.com',
    iosClientId: '43506521486-eisiuhs8p5dsvtsbvtunb2ea361730ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp1',
  );
}
